server:
  port: 8000
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
spring:
  application:
    name: exchange-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql:  true
    open-in-view: false
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/exchange_service}
    username: mydb
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  api-docs:
    path: /exchange-service/v3/api-docs
  swagger-ui:
    url: /exchange-service/v3/api-docs
  override-server-url: true


