server:
  port: 8765
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
spring:
  application:
    name: api-gateway
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/book-service/**
            - id: exchange-service
              uri: lb://exchange-service
              predicates:
                - Path=/exchange-service/**
springdoc:
  swagger-ui:
    urls:
      - name: exchange-service
        url: /exchange-service/v3/api-docs
      - name: book-service
        url: /book-service/v3/api-docs

#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true
