server:
  port: 8100
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 1

  retry:
    instances:
      foo-bar:
        max-attempts: 7
        wait-duration: 1s
        enable-exponential-backoff: true
spring:
  application:
    name: book-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql:  true
    open-in-view: false
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/book_service}
    username: mydb
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    url: /book-service/v3/api-docs
  override-server-url: true